services:
  postgres:
    image: postgres:13
    container_name: it-asset-postgres-ci
    environment:
      POSTGRES_DB: it_asset_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - it-asset-network-ci
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: it-asset-app-ci
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: it_asset_inventory
      DB_USER: postgres
      DB_PASSWORD: password
      LOG_LEVEL: info
    ports:
      - "3001:3000"
    networks:
      - it-asset-network-ci
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

networks:
  it-asset-network-ci:
    driver: bridge